CRITICAL - 2022-11-05 12:18:16 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 224.
 1 SYSTEMPATH\CodeIgniter.php(224): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(182): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2022-11-05 12:19:45 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 224.
 1 SYSTEMPATH\CodeIgniter.php(224): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(182): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2022-11-05 12:34:27 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 224.
 1 SYSTEMPATH\CodeIgniter.php(224): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(182): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2022-11-05 12:47:49 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 224.
 1 SYSTEMPATH\CodeIgniter.php(224): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(182): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 ROOTPATH\spark(83): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2022-11-05 07:49:57 --> Class "App\Controllers\FakultasModel" not found
in APPPATH\Controllers\Home.php on line 16.
 1 SYSTEMPATH\CodeIgniter.php(889): App\Controllers\Home->__construct()
 2 SYSTEMPATH\CodeIgniter.php(473): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 07:50:14 --> Class "App\Controllers\FakultasModel" not found
in APPPATH\Controllers\Home.php on line 16.
 1 SYSTEMPATH\CodeIgniter.php(889): App\Controllers\Home->__construct()
 2 SYSTEMPATH\CodeIgniter.php(473): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 07:50:15 --> Class "App\Controllers\FakultasModel" not found
in APPPATH\Controllers\Home.php on line 16.
 1 SYSTEMPATH\CodeIgniter.php(889): App\Controllers\Home->__construct()
 2 SYSTEMPATH\CodeIgniter.php(473): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 07:50:40 --> Class "App\Controllers\FakultasModel" not found
in APPPATH\Controllers\Home.php on line 16.
 1 SYSTEMPATH\CodeIgniter.php(889): App\Controllers\Home->__construct()
 2 SYSTEMPATH\CodeIgniter.php(473): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 08:41:13 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 08:41:13 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'TEKNIK SIPIL\', \'2022-11-05 08:41:13\', \'2022-11-05 08:41:13\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'TEKNIK SIPIL\', \'2022-11-05 08:41:13\', \'2022-11-05 08:41:13\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'TEKNIK SIPIL\', \'2022-11-05 08:41:13\', \'2022-11-05 08:41:13\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 08:50:28 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 08:50:28 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 08:50:28\', \'2022-11-05 08:50:28\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 08:50:28\', \'2022-11-05 08:50:28\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 08:50:28\', \'2022-11-05 08:50:28\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 08:51:51 --> Call to undefined method CodeIgniter\Router\RouteCollection::pos()
in APPPATH\Config\Routes.php on line 41.
 1 SYSTEMPATH\CodeIgniter.php(789): require()
 2 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 3 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 08:51:53 --> Call to undefined method CodeIgniter\Router\RouteCollection::pos()
in APPPATH\Config\Routes.php on line 41.
 1 SYSTEMPATH\CodeIgniter.php(789): require()
 2 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 3 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 08:51:55 --> Call to undefined method CodeIgniter\Router\RouteCollection::pos()
in APPPATH\Config\Routes.php on line 41.
 1 SYSTEMPATH\CodeIgniter.php(789): require()
 2 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 3 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 08:53:19 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 08:53:19 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 08:53:19\', \'2022-11-05 08:53:19\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 08:53:19\', \'2022-11-05 08:53:19\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 08:53:19\', \'2022-11-05 08:53:19\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 08:57:51 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 08:57:51 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 08:57:51\', \'2022-11-05 08:57:51\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 08:57:51\', \'2022-11-05 08:57:51\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 08:57:51\', \'2022-11-05 08:57:51\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 08:58:29 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 08:58:29 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'53klkj\', \'jlkjk;\', \'2022-11-05 08:58:29\', \'2022-11-05 08:58:29\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'53klkj\', \'jlkjk;\', \'2022-11-05 08:58:29\', \'2022-11-05 08:58:29\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'53klkj\', \'jlkjk;\', \'2022-11-05 08:58:29\', \'2022-11-05 08:58:29\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 09:01:37 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 09:02:12 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 09:02:19 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 09:02:21 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 09:02:37 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 09:03:33 --> Invalid file: fakultas/create.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/create.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/create', [], true)
 3 APPPATH\Controllers\Fakultas.php(24): view('fakultas/create')
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->create()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 09:03:36 --> Invalid file: fakultas/create.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/create.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/create', [], true)
 3 APPPATH\Controllers\Fakultas.php(24): view('fakultas/create')
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->create()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 09:03:41 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 09:03:43 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 09:04:34 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 09:04:47 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 09:05:08 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 09:06:14 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 09:06:16 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 09:06:19 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 09:08:44 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 09:08:44 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'fakultas\', \'2022-11-05 09:08:44\', \'2022-11-05 09:08:44\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'fakultas\', \'2022-11-05 09:08:44\', \'2022-11-05 09:08:44\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'fakultas\', \'2022-11-05 09:08:44\', \'2022-11-05 09:08:44\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 09:29:19 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 09:29:19 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 09:29:19\', \'2022-11-05 09:29:19\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 09:29:19\', \'2022-11-05 09:29:19\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 09:29:19\', \'2022-11-05 09:29:19\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 09:32:12 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `fakulta...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `fakulta...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `fakulta...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `fakulta...', Array, false)
#4 D:\web\code\inventory\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 D:\web\code\inventory\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\web\code\inventory\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(82): CodeIgniter\Model->update('FADIB', Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->update('FADIB')
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 09:32:12 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `fakultas` SET `kode_fakultas` = NULL, `nama_fakultas` = \'Adab dan Ilmu Budaya Bangsa\', `updated_at` = \'2022-11-05 09:32:12\'
WHERE `fakultas`.`kode_fakultas` IN (\'FADIB\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `fakultas` SET `kode_fakultas` = NULL, `nama_fakultas` = \'Adab dan Ilmu Budaya Bangsa\', `updated_at` = \'2022-11-05 09:32:12\'
WHERE `fakultas`.`kode_fakultas` IN (\'FADIB\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `fakultas` SET `kode_fakultas` = NULL, `nama_fakultas` = \'Adab dan Ilmu Budaya Bangsa\', `updated_at` = \'2022-11-05 09:32:12\'
WHERE `fakultas`.`kode_fakultas` IN (\'FADIB\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `fakultas` SET `kode_fakultas` = :kode_fakultas:, `nama_fakultas` = :nama_fakultas:, `updated_at` = :updated_at:
WHERE `fakultas`.`kode_fakultas` IN :fakultas.kode_fakultas:', [...], false)
 5 SYSTEMPATH\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(886): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Fakultas.php(82): CodeIgniter\Model->update('FADIB', [...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->update('FADIB')
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 09:32:33 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `fakulta...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `fakulta...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `fakulta...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `fakulta...', Array, false)
#4 D:\web\code\inventory\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 D:\web\code\inventory\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\web\code\inventory\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(82): CodeIgniter\Model->update('FADIB', Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->update('FADIB')
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 09:32:33 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `fakultas` SET `kode_fakultas` = NULL, `nama_fakultas` = \'Adab dan Ilmu Budayan\', `updated_at` = \'2022-11-05 09:32:33\'
WHERE `fakultas`.`kode_fakultas` IN (\'FADIB\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `fakultas` SET `kode_fakultas` = NULL, `nama_fakultas` = \'Adab dan Ilmu Budayan\', `updated_at` = \'2022-11-05 09:32:33\'
WHERE `fakultas`.`kode_fakultas` IN (\'FADIB\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `fakultas` SET `kode_fakultas` = NULL, `nama_fakultas` = \'Adab dan Ilmu Budayan\', `updated_at` = \'2022-11-05 09:32:33\'
WHERE `fakultas`.`kode_fakultas` IN (\'FADIB\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `fakultas` SET `kode_fakultas` = :kode_fakultas:, `nama_fakultas` = :nama_fakultas:, `updated_at` = :updated_at:
WHERE `fakultas`.`kode_fakultas` IN :fakultas.kode_fakultas:', [...], false)
 5 SYSTEMPATH\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(886): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Fakultas.php(82): CodeIgniter\Model->update('FADIB', [...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->update('FADIB')
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 09:33:00 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 09:33:00 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'dffsd\', \'2022-11-05 09:33:00\', \'2022-11-05 09:33:00\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'dffsd\', \'2022-11-05 09:33:00\', \'2022-11-05 09:33:00\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'dffsd\', \'2022-11-05 09:33:00\', \'2022-11-05 09:33:00\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 09:33:05 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 09:33:05 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'dffsd\', \'2022-11-05 09:33:05\', \'2022-11-05 09:33:05\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'dffsd\', \'2022-11-05 09:33:05\', \'2022-11-05 09:33:05\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'dffsd\', \'2022-11-05 09:33:05\', \'2022-11-05 09:33:05\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 09:36:37 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 09:36:37 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'Fakultas\', \'2022-11-05 09:36:37\', \'2022-11-05 09:36:37\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'Fakultas\', \'2022-11-05 09:36:37\', \'2022-11-05 09:36:37\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'Fakultas\', \'2022-11-05 09:36:37\', \'2022-11-05 09:36:37\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 09:37:22 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `fakulta...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `fakulta...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `fakulta...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `fakulta...', Array, false)
#4 D:\web\code\inventory\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 D:\web\code\inventory\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 D:\web\code\inventory\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(82): CodeIgniter\Model->update('FADIB', Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->update('FADIB')
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 09:37:22 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `fakultas` SET `kode_fakultas` = NULL, `nama_fakultas` = \'Adab dan Ilmu Budaya\', `updated_at` = \'2022-11-05 09:37:22\'
WHERE `fakultas`.`kode_fakultas` IN (\'FADIB\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `fakultas` SET `kode_fakultas` = NULL, `nama_fakultas` = \'Adab dan Ilmu Budaya\', `updated_at` = \'2022-11-05 09:37:22\'
WHERE `fakultas`.`kode_fakultas` IN (\'FADIB\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `fakultas` SET `kode_fakultas` = NULL, `nama_fakultas` = \'Adab dan Ilmu Budaya\', `updated_at` = \'2022-11-05 09:37:22\'
WHERE `fakultas`.`kode_fakultas` IN (\'FADIB\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `fakultas` SET `kode_fakultas` = :kode_fakultas:, `nama_fakultas` = :nama_fakultas:, `updated_at` = :updated_at:
WHERE `fakultas`.`kode_fakultas` IN :fakultas.kode_fakultas:', [...], false)
 5 SYSTEMPATH\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(886): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Fakultas.php(82): CodeIgniter\Model->update('FADIB', [...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->update('FADIB')
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 10:08:39 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 10:08:39 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'fakultas\', \'2022-11-05 10:08:39\', \'2022-11-05 10:08:39\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'fakultas\', \'2022-11-05 10:08:39\', \'2022-11-05 10:08:39\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'fakultas\', \'2022-11-05 10:08:39\', \'2022-11-05 10:08:39\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 10:10:14 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 10:10:14 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'56\', \'jhjhl\', \'2022-11-05 10:10:14\', \'2022-11-05 10:10:14\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'56\', \'jhjhl\', \'2022-11-05 10:10:14\', \'2022-11-05 10:10:14\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'56\', \'jhjhl\', \'2022-11-05 10:10:14\', \'2022-11-05 10:10:14\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 10:11:05 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 10:11:05 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'fakultas\', \'2022-11-05 10:11:05\', \'2022-11-05 10:11:05\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'fakultas\', \'2022-11-05 10:11:05\', \'2022-11-05 10:11:05\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'fakultas\', \'2022-11-05 10:11:05\', \'2022-11-05 10:11:05\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 10:15:10 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 10:15:10 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'67\', \'kjkjlk\', \'2022-11-05 10:15:10\', \'2022-11-05 10:15:10\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'67\', \'kjkjlk\', \'2022-11-05 10:15:10\', \'2022-11-05 10:15:10\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'67\', \'kjkjlk\', \'2022-11-05 10:15:10\', \'2022-11-05 10:15:10\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 10:15:41 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 10:15:41 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'67\', \'kjkjlk\', \'2022-11-05 10:15:41\', \'2022-11-05 10:15:41\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'67\', \'kjkjlk\', \'2022-11-05 10:15:41\', \'2022-11-05 10:15:41\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'67\', \'kjkjlk\', \'2022-11-05 10:15:41\', \'2022-11-05 10:15:41\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 10:15:51 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 10:15:51 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'uiu\', \'kjlkjlj\', \'2022-11-05 10:15:51\', \'2022-11-05 10:15:51\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'uiu\', \'kjlkjlj\', \'2022-11-05 10:15:51\', \'2022-11-05 10:15:51\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'uiu\', \'kjlkjlj\', \'2022-11-05 10:15:51\', \'2022-11-05 10:15:51\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 10:23:04 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 10:23:04 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'TEKNIK\', \'2022-11-05 10:23:04\', \'2022-11-05 10:23:04\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'TEKNIK\', \'2022-11-05 10:23:04\', \'2022-11-05 10:23:04\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'TEKNIK\', \'2022-11-05 10:23:04\', \'2022-11-05 10:23:04\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 10:23:19 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 10:23:19 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'hjhlkhlhjl\', \'2022-11-05 10:23:19\', \'2022-11-05 10:23:19\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'hjhlkhlhjl\', \'2022-11-05 10:23:19\', \'2022-11-05 10:23:19\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'hjhlkhlhjl\', \'2022-11-05 10:23:19\', \'2022-11-05 10:23:19\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 10:26:42 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 10:26:42 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'42\', \'tESD\', \'2022-11-05 10:26:42\', \'2022-11-05 10:26:42\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'42\', \'tESD\', \'2022-11-05 10:26:42\', \'2022-11-05 10:26:42\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'42\', \'tESD\', \'2022-11-05 10:26:42\', \'2022-11-05 10:26:42\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 10:27:07 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(50): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 10:27:07 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'76\', \'kjkjkj\', \'2022-11-05 10:27:07\', \'2022-11-05 10:27:07\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'76\', \'kjkjkj\', \'2022-11-05 10:27:07\', \'2022-11-05 10:27:07\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'76\', \'kjkjkj\', \'2022-11-05 10:27:07\', \'2022-11-05 10:27:07\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(50): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 10:40:39 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(52): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 10:40:39 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'TEknik\', \'2022-11-05 10:40:39\', \'2022-11-05 10:40:39\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'TEknik\', \'2022-11-05 10:40:39\', \'2022-11-05 10:40:39\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'TEknik\', \'2022-11-05 10:40:39\', \'2022-11-05 10:40:39\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(52): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 10:43:44 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(52): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 10:43:44 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'341\', \'TEKNIK\', \'2022-11-05 10:43:44\', \'2022-11-05 10:43:44\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'341\', \'TEKNIK\', \'2022-11-05 10:43:44\', \'2022-11-05 10:43:44\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'341\', \'TEKNIK\', \'2022-11-05 10:43:44\', \'2022-11-05 10:43:44\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(52): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 10:51:02 --> Undefined variable $validation
in APPPATH\Controllers\Fakultas.php on line 48.
 1 APPPATH\Controllers\Fakultas.php(48): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $validation', 'APPPATH\\Controllers\\Fakultas.php', 48)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 10:51:08 --> Undefined variable $validation
in APPPATH\Controllers\Fakultas.php on line 48.
 1 APPPATH\Controllers\Fakultas.php(48): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $validation', 'APPPATH\\Controllers\\Fakultas.php', 48)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 10:57:55 --> Undefined variable $validation
in APPPATH\Controllers\Fakultas.php on line 48.
 1 APPPATH\Controllers\Fakultas.php(48): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $validation', 'APPPATH\\Controllers\\Fakultas.php', 48)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 10:58:11 --> Undefined variable $validation
in APPPATH\Controllers\Fakultas.php on line 48.
 1 APPPATH\Controllers\Fakultas.php(48): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $validation', 'APPPATH\\Controllers\\Fakultas.php', 48)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 10:59:06 --> Undefined variable $validation
in APPPATH\Controllers\Fakultas.php on line 48.
 1 APPPATH\Controllers\Fakultas.php(48): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $validation', 'APPPATH\\Controllers\\Fakultas.php', 48)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:00:06 --> Undefined variable $validation
in APPPATH\Controllers\Fakultas.php on line 48.
 1 APPPATH\Controllers\Fakultas.php(48): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $validation', 'APPPATH\\Controllers\\Fakultas.php', 48)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 11:02:49 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(54): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 11:02:49 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'TEKNIK\', \'2022-11-05 11:02:49\', \'2022-11-05 11:02:49\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'TEKNIK\', \'2022-11-05 11:02:49\', \'2022-11-05 11:02:49\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'TEKNIK\', \'2022-11-05 11:02:49\', \'2022-11-05 11:02:49\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 11:05:42 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(54): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 11:05:42 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'Fakultas\', \'2022-11-05 11:05:42\', \'2022-11-05 11:05:42\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'Fakultas\', \'2022-11-05 11:05:42\', \'2022-11-05 11:05:42\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'Fakultas\', \'2022-11-05 11:05:42\', \'2022-11-05 11:05:42\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 11:06:59 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(54): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 11:06:59 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41mk\', \'amll\', \'2022-11-05 11:06:59\', \'2022-11-05 11:06:59\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41mk\', \'amll\', \'2022-11-05 11:06:59\', \'2022-11-05 11:06:59\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41mk\', \'amll\', \'2022-11-05 11:06:59\', \'2022-11-05 11:06:59\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:09:59 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:10:00 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:10:02 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:10:03 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:10:20 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:10:21 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:10:38 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:11:15 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:11:29 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:11:47 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:11:59 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:12:22 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:12:40 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:13:12 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:13:14 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:13:18 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:13:30 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:13:45 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:15:00 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:15:02 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:15:08 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(20): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:15:55 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:15:57 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:16:00 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:16:30 --> Undefined variable $data
in APPPATH\Controllers\Fakultas.php on line 19.
 1 APPPATH\Controllers\Fakultas.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'APPPATH\\Controllers\\Fakultas.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:16:33 --> Undefined variable $data
in APPPATH\Controllers\Fakultas.php on line 19.
 1 APPPATH\Controllers\Fakultas.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'APPPATH\\Controllers\\Fakultas.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:18:25 --> Invalid file: fakultas/index.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('fakultas/index.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 3 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:19:39 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:19:46 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:20:55 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
CRITICAL - 2022-11-05 11:21:13 --> Attempt to read property "kode_fakultas" on array
in APPPATH\Views\fakultas\index.php on line 32.
 1 APPPATH\Views\fakultas\index.php(32): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "kode_fakultas" on array', 'APPPATH\\Views\\fakultas\\index.php', 32)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\fakultas\\index.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('fakultas/index', [], true)
 5 APPPATH\Controllers\Fakultas.php(19): view('fakultas/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->index()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 11:21:29 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(53): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 11:21:29 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 11:21:29\', \'2022-11-05 11:21:29\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 11:21:29\', \'2022-11-05 11:21:29\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 11:21:29\', \'2022-11-05 11:21:29\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 11:22:20 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(53): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 11:22:20 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 11:22:20\', \'2022-11-05 11:22:20\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 11:22:20\', \'2022-11-05 11:22:20\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'41\', \'teknik\', \'2022-11-05 11:22:20\', \'2022-11-05 11:22:20\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(53): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-05 11:24:46 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\web\code\inventory\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fa...', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fa...')
#2 D:\web\code\inventory\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fa...')
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fa...', Array, false)
#4 D:\web\code\inventory\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\web\code\inventory\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 D:\web\code\inventory\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\web\code\inventory\app\Controllers\Fakultas.php(54): CodeIgniter\Model->insert(Array)
#8 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Fakultas->store()
#9 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
#10 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#13 {main}
CRITICAL - 2022-11-05 11:24:46 --> Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'42\', \'teknnik\', \'2022-11-05 11:24:46\', \'2022-11-05 11:24:46\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'42\', \'teknnik\', \'2022-11-05 11:24:46\', \'2022-11-05 11:24:46\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (\'42\', \'teknnik\', \'2022-11-05 11:24:46\', \'2022-11-05 11:24:46\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fakultas` (`kode_fakultas`, `nama_fakultas`, `created_at`, `updated_at`) VALUES (:kode_fakultas:, :nama_fakultas:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Fakultas.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Fakultas->store()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fakultas))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
