ERROR - 2022-11-08 05:24:42 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\web\code\inventory\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'test', 'test', 'inventaris_proj...', 3306, '', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\web\code\inventory\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\web\code\inventory\app\Models\Inventory_FakultasModel.php(49): CodeIgniter\Database\BaseBuilder->get()
#5 D:\web\code\inventory\app\Controllers\Inventory_fakultas.php(19): App\Models\Inventory_FakultasModel->getBarang1(NULL)
#6 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Inventory_fakultas->index()
#7 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Inventory_fakultas))
#8 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\web\code\inventory\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\web\code\inventory\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\web\code\inventory\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\web\code\inventory\app\Models\Inventory_FakultasModel.php(49): CodeIgniter\Database\BaseBuilder->get()
#4 D:\web\code\inventory\app\Controllers\Inventory_fakultas.php(19): App\Models\Inventory_FakultasModel->getBarang1(NULL)
#5 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Inventory_fakultas->index()
#6 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Inventory_fakultas))
#7 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#10 {main}
CRITICAL - 2022-11-08 05:24:42 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `inventory_fakultas`
JOIN `fakultas` ON `fakultas`.`kode_fakultas`=`inventory_fakultas`.`kode_fakultas`
JOIN `ruang` ON `ruang`.`kode_ruang`=`inventory_fakultas`.`kode_ruang`', [], false)
 3 APPPATH\Models\Inventory_FakultasModel.php(49): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Inventory_fakultas.php(19): App\Models\Inventory_FakultasModel->getBarang1(null)
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Inventory_fakultas->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Inventory_fakultas))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-08 05:24:46 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\web\code\inventory\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'test', 'test', 'inventaris_proj...', 3306, '', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\web\code\inventory\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\web\code\inventory\app\Models\Inventory_FakultasModel.php(49): CodeIgniter\Database\BaseBuilder->get()
#5 D:\web\code\inventory\app\Controllers\Inventory_fakultas.php(19): App\Models\Inventory_FakultasModel->getBarang1(NULL)
#6 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Inventory_fakultas->index()
#7 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Inventory_fakultas))
#8 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\web\code\inventory\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\web\code\inventory\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\web\code\inventory\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\web\code\inventory\app\Models\Inventory_FakultasModel.php(49): CodeIgniter\Database\BaseBuilder->get()
#4 D:\web\code\inventory\app\Controllers\Inventory_fakultas.php(19): App\Models\Inventory_FakultasModel->getBarang1(NULL)
#5 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Inventory_fakultas->index()
#6 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Inventory_fakultas))
#7 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#10 {main}
CRITICAL - 2022-11-08 05:24:46 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `inventory_fakultas`
JOIN `fakultas` ON `fakultas`.`kode_fakultas`=`inventory_fakultas`.`kode_fakultas`
JOIN `ruang` ON `ruang`.`kode_ruang`=`inventory_fakultas`.`kode_ruang`', [], false)
 3 APPPATH\Models\Inventory_FakultasModel.php(49): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Inventory_fakultas.php(19): App\Models\Inventory_FakultasModel->getBarang1(null)
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Inventory_fakultas->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Inventory_fakultas))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-08 05:24:50 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\web\code\inventory\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'test', 'test', 'inventaris_proj...', 3306, '', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\web\code\inventory\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\web\code\inventory\app\Models\Inventory_FakultasModel.php(49): CodeIgniter\Database\BaseBuilder->get()
#5 D:\web\code\inventory\app\Controllers\Inventory_fakultas.php(19): App\Models\Inventory_FakultasModel->getBarang1(NULL)
#6 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Inventory_fakultas->index()
#7 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Inventory_fakultas))
#8 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\web\code\inventory\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\web\code\inventory\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\web\code\inventory\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\web\code\inventory\app\Models\Inventory_FakultasModel.php(49): CodeIgniter\Database\BaseBuilder->get()
#4 D:\web\code\inventory\app\Controllers\Inventory_fakultas.php(19): App\Models\Inventory_FakultasModel->getBarang1(NULL)
#5 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Inventory_fakultas->index()
#6 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Inventory_fakultas))
#7 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#10 {main}
CRITICAL - 2022-11-08 05:24:50 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `inventory_fakultas`
JOIN `fakultas` ON `fakultas`.`kode_fakultas`=`inventory_fakultas`.`kode_fakultas`
JOIN `ruang` ON `ruang`.`kode_ruang`=`inventory_fakultas`.`kode_ruang`', [], false)
 3 APPPATH\Models\Inventory_FakultasModel.php(49): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Inventory_fakultas.php(19): App\Models\Inventory_FakultasModel->getBarang1(null)
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Inventory_fakultas->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Inventory_fakultas))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-08 05:25:06 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\web\code\inventory\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'test', 'test', 'inventaris_proj...', 3306, '', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\web\code\inventory\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\web\code\inventory\app\Models\Inventory_FakultasModel.php(49): CodeIgniter\Database\BaseBuilder->get()
#5 D:\web\code\inventory\app\Controllers\Inventory_fakultas.php(19): App\Models\Inventory_FakultasModel->getBarang1(NULL)
#6 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Inventory_fakultas->index()
#7 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Inventory_fakultas))
#8 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\web\code\inventory\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\web\code\inventory\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\web\code\inventory\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\web\code\inventory\app\Models\Inventory_FakultasModel.php(49): CodeIgniter\Database\BaseBuilder->get()
#4 D:\web\code\inventory\app\Controllers\Inventory_fakultas.php(19): App\Models\Inventory_FakultasModel->getBarang1(NULL)
#5 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Inventory_fakultas->index()
#6 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Inventory_fakultas))
#7 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#10 {main}
CRITICAL - 2022-11-08 05:25:06 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `inventory_fakultas`
JOIN `fakultas` ON `fakultas`.`kode_fakultas`=`inventory_fakultas`.`kode_fakultas`
JOIN `ruang` ON `ruang`.`kode_ruang`=`inventory_fakultas`.`kode_ruang`', [], false)
 3 APPPATH\Models\Inventory_FakultasModel.php(49): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Inventory_fakultas.php(19): App\Models\Inventory_FakultasModel->getBarang1(null)
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Inventory_fakultas->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Inventory_fakultas))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-08 05:25:51 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\web\code\inventory\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'test', 'test', 'inventaris_proj...', 3306, '', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\web\code\inventory\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\web\code\inventory\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 D:\web\code\inventory\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 D:\web\code\inventory\app\Controllers\Login.php(20): CodeIgniter\BaseModel->first()
#7 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Login->auth()
#8 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\web\code\inventory\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\web\code\inventory\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\web\code\inventory\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\web\code\inventory\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 D:\web\code\inventory\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 D:\web\code\inventory\app\Controllers\Login.php(20): CodeIgniter\BaseModel->first()
#6 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Login->auth()
#7 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#11 {main}
CRITICAL - 2022-11-08 05:25:51 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `user_email` = :user_email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Login.php(20): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Login->auth()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-11-08 05:26:57 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\web\code\inventory\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\web\code\inventory\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'test', 'test', 'inventaris_proj...', 3306, '', 0)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\web\code\inventory\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\web\code\inventory\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\web\code\inventory\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#5 D:\web\code\inventory\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#6 D:\web\code\inventory\app\Controllers\Login.php(20): CodeIgniter\BaseModel->first()
#7 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Login->auth()
#8 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\web\code\inventory\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\web\code\inventory\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\web\code\inventory\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\web\code\inventory\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\web\code\inventory\system\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
#4 D:\web\code\inventory\system\BaseModel.php(623): CodeIgniter\Model->doFirst()
#5 D:\web\code\inventory\app\Controllers\Login.php(20): CodeIgniter\BaseModel->first()
#6 D:\web\code\inventory\system\CodeIgniter.php(927): App\Controllers\Login->auth()
#7 D:\web\code\inventory\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 D:\web\code\inventory\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\web\code\inventory\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 D:\web\code\inventory\system\Commands\Server\rewrite.php(46): require_once('D:\\web\\code\\inv...')
#11 {main}
CRITICAL - 2022-11-08 05:26:57 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `user_email` IS NULL
 LIMIT 1', [], false)
 3 SYSTEMPATH\Model.php(250): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(623): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Login.php(20): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Login->auth()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
